### ISSUE TITLE
Missing documentation for migrations table

### ISSUE THREAD

**Issue by simplenotezy** [goldspecdigital/laravel-eloquent-uuid#16]
Great package! I'm just missing some documentation on how the migrations table should look like.

I used to use:

    $table->uuid('user_id');

But I am getting error:

    SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1

When inserting data. I assume this is because of a wrong type?

**Comment by simplenotezy** [comment]
I realized I had accidentally added the `uuid` method to the wrong property. Anyhow still believe some migration information could be helpful to newcomers ;)

**Comment by matthew-inamdar** [comment]
Hey @simplenotezy 👋 

Am I right in thinking your suggestion is to provide some guidance on how to setup the migrations to support a UUID primary key? Or have I misunderstood?

**Comment by gheleri** [comment]
Definitely this doc is missing. I'm facing the same problem.

**Comment by matthew-inamdar** [comment]
Hey @gheleri 👋 

If you could confirm, is it the lack of documentation regarding setting up the database migrations which you are referring to?

**Comment by gheleri** [comment]
Yes. I can make a pull request with the updated readme.

**Comment by matthew-inamdar** [comment]
@gheleri I thought that may have been the case 😄 

Not to worry, I'll update the `README.md` now and publish a new patch release.

**Comment by gheleri** [comment]
Ok. Thanks btw and congratulations to this package :)

**Comment by matthew-inamdar** [comment]
@gheleri and @simplenotezy I've got a PR ready to merge in if you could please first check the `README.md` has sufficient information here: https://github.com/goldspecdigital/laravel-eloquent-uuid/blob/feature/add-migration-docs/README.md#user-content-database-migrations

**Comment by gheleri** [comment]
@matthew-inamdar I reply your pull request. Feel free to make any changes.

**Comment by matthew-inamdar** [comment]
This has been added in [v6.1.2](https://github.com/goldspecdigital/laravel-eloquent-uuid/releases/tag/v6.1.2)
