### ISSUE TITLE
uuid:make:model fails in case sensitive filesystems

### ISSUE THREAD

**Issue by jantoniomartin** [goldspecdigital/laravel-eloquent-uuid#18]
When running `uuid:make:model` in a Linux system, a FileNotFoundException is raised.

The code looks for a 'stubs' directory (with lowercase 's'), and the directory `src/Console/Stubs` (with uppercase 's') is not found. A simple solution would be changing this directory to a lowercase name.

**Comment by matthew-inamdar** [comment]
Hey @jantoniomartin 👋

Thanks for making us aware of this issue! A PR is currently underway to fix this in the next patch release.

**Comment by matthew-inamdar** [comment]
This has been fixed in [v6.1.2](https://github.com/goldspecdigital/laravel-eloquent-uuid/releases/tag/v6.1.2)
