### ISSUE TITLE
Add artisan command

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/laravel-eloquent-uuid#2]
An artisan command should be provided which creates a model using this class. If possible, we should have this override the standard Laravel command - and it should be configurable so you can choose whether to override it or not.

**Comment by Taalaybek** [comment]
It will be geat

**Comment by matthew-inamdar** [comment]
I'm thinking of creating a command under our vendor namespace (`uuid:make:model`) rather than override the official `make:model` one as this may cause unforeseen issues.

There's also several configurations I want to provide as part of this, such as whether or not to include strict types in the created models, as I'm aware not all developers make use of this. Will hopefully work on this tonight!

**Comment by nathanaelytj** [comment]
Hello. I saw this issue and I want to help. I have created the command `uuid:make:model` and will create pull request. We can discuss in more details there.
