### ISSUE TITLE
Alternative trait instead of extending class

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/laravel-eloquent-uuid#21]
Following the proposal of #20, we should definitely add a trait as an alternative to extending the classes provided.

This flexibility allows this package to still be utilised in the event that the client code is already extending their models from a class provided in another package.

This will need to be documented in the `README.md`.

**Comment by firmantr3** [comment]
That would be nice! 👍

**Comment by matthew-inamdar** [comment]
@firmantr3 I've created a PR to add trait support. Please check out the docs and give feedback:

Docs: https://github.com/goldspecdigital/laravel-eloquent-uuid/blob/feature/trait/README.md
PR: #22
