### ISSUE TITLE
Backport Uuid trait to Laravel v5.8

### ISSUE THREAD

**Issue by glenncoppens** [goldspecdigital/laravel-eloquent-uuid#25]
Hi there,

Am I right if I think the Uuid trait is not available for laravel 5.8.* (using v1.1.0)?
Would it be possible to backport this? Or are there specific reasons to not go there? :)

Thanks,
Glenn

**Comment by matthew-inamdar** [comment]
Hey @glenncoppens 👋 

Yeah, that's right, it's not available on that major version.

There's no reason for not backporting, apart from not having the time. I'll keep this open and look at adding this in over the next few days.

Cheers,
Matt

**Comment by matthew-inamdar** [comment]
Ah, just seen your PR, will review shortly 🙂

**Comment by matthew-inamdar** [comment]
Merged and released in https://github.com/goldspecdigital/laravel-eloquent-uuid/releases/tag/v1.2.0
