### ISSUE TITLE
Create UUID in seeder

### ISSUE THREAD

**Issue by robertnicjoo** [goldspecdigital/laravel-eloquent-uuid#29]
How can I create UUID in seeder file?

### Sample

```php
       DB::table('brands')->delete();

        $brands = array(
            array(
                'id' => '',  // how to create this?
                'name' => 'No Brand',
                'slug' => 'no-brand',
                'description' => null,
                'photo' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ),
        );
        
        DB::table('brands')->insert($brands);
```

**Comment by bk987** [comment]
```php
'id' => \Ramsey\Uuid\Uuid::uuid4()->toString(),
```

**Comment by robertnicjoo** [comment]
> ```
> 'id' => \Ramsey\Uuid\Uuid::uuid4()->toString(),   
> ```

Why `Ramsey`? this package name is `goldspecdigital`

**Comment by matthew-inamdar** [comment]
@robertnicjoo Laravel already uses https://github.com/ramsey/uuid - which is also what this package uses.

https://github.com/laravel/framework/blob/7.x/composer.json#L32

So I'd also agree with the solution @bk987 provided 🙂 

Closing for now, but happy to reopen if there's any further questions you have.

**Comment by RVP04** [comment]
can we use the goldspecdigital package also?

**Comment by matthew-inamdar** [comment]
@RVP04 This `goldspecdigital/laravel-eloquent-uuid` package makes use of the `ramsey/uuid` to generate the UUIDs.

This is because the `laravel/framework` package already requires is, so there's no need to recreate the wheel.
