### ISSUE TITLE
Is there anyway to provide default uuid v1?

### ISSUE THREAD

**Issue by imroca** [goldspecdigital/laravel-eloquent-uuid#3]
Is there anyway to default to other versions of uuid? Instead of creating uuid v4 create uuid v1?
This is just out of curiosity? Apache usergrid uuid default is v1 so if you would like to build something over that this would be great.

**Comment by matthew-inamdar** [comment]
@imroca yes we can definitely do this! Will look at getting this implemented over the next couple of days.
