### ISSUE TITLE
Event::fake() in tests prevents uuid being automatically generated

### ISSUE THREAD

**Issue by boptom** [goldspecdigital/laravel-eloquent-uuid#31]
Set up a feature test with the following (after setting up the uuid in the User model as per the documentation).
```
    /** @test */
    public function a_user_can_be_created()
    {
        Event::fake();

        $user = \App\User::create([
            'name' => 'J Smith',
            'email' => 'js@gmail.com',
            'password' => 'some_pass',
        ]);

         dd($user->id);
    }
```

Will result in an SQL error:
```
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value
```

Remove the `Event::fake();` line and it works as expected, outputting the user's uuid.

Is there a way to use this and still use the event fakes in tests?

**Comment by matthew-inamdar** [comment]
Hi @boptom 👋 

This is due to the boot event now being faked, which is what this package relies on.

There is a way to fake only certain events which may prove to be more useful for your tests, but I can't remember how I achieved that off the top of my head!

I'll have a look and see if I can dig up some code examples for you.

**Comment by boptom** [comment]
Thanks for the prompt reply @matthew-inamdar, and your work here. For anyone else who comes across this an example of faking certain events looks like this:

```
    Event::fake([
        OrderCreated::class,
    ]);
```

See the section heading "Faking a Subset of Events" here: https://laravel.com/docs/master/mocking#event-fake

You can also call `Event::fake();` after using factories in some test cases.

Thanks again!
