### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by jonathanTQZ** [goldspecdigital/laravel-eloquent-uuid#37]
Hello, 

there is a security against duplicates ?

**Comment by matthew-inamdar** [comment]
@jonathanTQZ The chance of collision with a v4 UUID is 10^-37. The chances are you'll never encounter a collision, but if you do, I'd recommend wrapping your DB statements in a transaction and implementing graceful error handling/retries.

The only way to truly prevent a collision would be to first perform a query to check a record already exists with the same UUID, which is extra overhead that's not needed.

However, this can still be achieved by overriding the `generateUuid()` method.

**Comment by jonathanTQZ** [comment]
@matthew-inamdar ok, thank :)
