### ISSUE TITLE
UUID on pivot

### ISSUE THREAD

**Issue by jayenne** [goldspecdigital/laravel-eloquent-uuid#40]
hi,
is there a way of creating uuid on pivot?
on seeding, I'm getting `General error: 1364 Field 'id' doesn't have a default value`

my model is..
```
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model;
class BoardPost extends Model
{
    use Uuid;
    
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'id';
    
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $uuid = (string) Uuid::generate(4);
            $model->id = $uuid;
        });
    }
}

```

**Comment by matthew-inamdar-sky** [comment]
Hi @jayenne 👋 

Please take a look at this comment - hopefully, it answers your question: https://github.com/goldspecdigital/laravel-eloquent-uuid/issues/33#issuecomment-681125030

**Comment by matthew-inamdar** [comment]
@jayenne Did that help? I'll close this issue if so.

**Comment by matthew-inamdar** [comment]
Closing due to no reply.
