### ISSUE TITLE
php8 compatibility 

### ISSUE THREAD

**Issue by Gerbenodk** [goldspecdigital/laravel-eloquent-uuid#42]
atm this packages doesn't allow me to upgrade to php8 :(

**Comment by Gerbenodk** [comment]
I fixed it by running:
composer require goldspecdigital/laravel-eloquent-uuid:^8.0 --ignore-platform-reqs

**Comment by jefersonralmeida** [comment]
I installed the package ignoring the platform requirements but would be nice to check and update the requirements.
