### ISSUE TITLE
$guarded must be array

### ISSUE THREAD

**Issue by icamys** [goldspecdigital/laravel-eloquent-uuid#45]
Hi! On version ^8.0 I'm getting an error:

```
Type of GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model::$guarded must be array 
(as in class Illuminate\Database\Eloquent\Model)
```

**Comment by matthew-inamdar** [comment]
@icamys have you declared the `$guarded` property on your model? Or their parent class?

**Comment by icamys** [comment]
@matthew-inamdar Sorry, I decided to not use this package. As far as I remember, as a workaround, I just added the `array` type to the line:
```
protected $guarded = [];
```
So it became:
```
protected array $guarded = [];
```
And it worked for me.
