### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by davisriska** [goldspecdigital/laravel-eloquent-uuid#48]
I see that there is already a pull request to support Laravel 9 #47.
Any estimates on when this will be merged and published?

Thank you for your work!

**Comment by matthew-inamdar** [comment]
Hey @davisriska. We just released Laravel 9 support in the latest release [v9.0.0](https://github.com/goldspecdigital/laravel-eloquent-uuid/releases/tag/v9.0.0).

**Comment by NicoHood** [comment]
Will this feature eventually merged upstream? Why isn't such a basic feature available upstream yet?

**Comment by matthew-inamdar** [comment]
@NicoHood I have no idea what you're talking about? Laravel 9 support has already been added.

**Comment by NicoHood** [comment]
Yeah, I am totally new to this, and my question must be totally stupid I guess.

I found that there is an uuid feature available upstream:
https://laravel.com/docs/9.x/migrations#column-method-uuid

Maybe you can explain the difference to that, I guess i completely missunderstand the usecase of this package?!
