### ISSUE TITLE
Support binary uuid

### ISSUE THREAD

**Issue by vaishnavmhetre** [goldspecdigital/laravel-eloquent-uuid#5]
String comparison of UUID is least recommended due to infamous cycles of comparison as compared to integer.
Support article - [Optimised UUID Storage](https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/)

Currently recommended repository [Laravel Efficient UUID](https://github.com/michaeldyrynda/laravel-efficient-uuid) be referred more of to get an idea of implementation.

Although not many repositories yet support uuid alternative as key identification of data, hence above alternative repository seemed more helpful. (They also have a [normal uuid repo](https://github.com/michaeldyrynda/laravel-model-uuid) too.)

I loved your ease of usage over their repo, hence suggesting their ideology and your accessibility, together, will be a big charm.

**Comment by matthew-inamdar** [comment]
This is a really useful solution for high performance requirements. However this package aims to be a simple solution for all. From what I can understand, the `binary()` column only supports a subset of the databases Eloquent supports?

**Comment by matthew-inamdar** [comment]
@vaishnavmhetre marking this as `wontfix` due to not having enough information. If you have any input then please reopen.

**Comment by blite** [comment]
should be on the readme as the index grows large extremely quickly with string types
