### ISSUE TITLE
Release for Laravel ^v6.0

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/laravel-eloquent-uuid#7]
With the new version of Laravel being released, we need to release a new version of the package which supports `^v6.0`.

Since Laravel has also switched to semantic versioning, the major version of the package should now match the version of Laravel it supports for simplicity.

**Comment by charlielangridge** [comment]
Any idea on when this will happen?

**Comment by matthew-inamdar** [comment]
> Any idea on when this will happen?

Looking at getting this done today.

**Comment by matthew-inamdar** [comment]
Support for Laravel v6.0 has been added as tag `v6.0.0`. All future versioning will use the same major and minor number for the supported Laravel version.
